### ISSUE TITLE
Question about the action space and specific control 

### ISSUE THREAD

**Issue by Chengfeng-Jia** [FanGShiYuu/CoDrivingLLM#2]
Hi, I really enjoy your paper; as always, it is very inspiring. 

While reading through the paper and the code, I encountered a point I’m unsure about. Specifically, I noticed that the action space is discrete, while the specific reference acceleration is continuous. Could you please explain how the limited discrete action space is mapped to the continuous reference?

**Comment by FanGShiYuu** [comment]
Thank you for your time and reading.
You are correct that we are using a discrete action space.
After producing discrete action will correspond to the acceleration, specific can see highway_env/vehicle/controller.py in class MDPVehicle act function (line218).
In addition, after generating the desired speed and speed, there is also a PID model to generate the final speed, you can see [highway-env controller](https://highway-env.farama.org/dynamics/vehicle/controller/) for more information.
We hope we have resolved your question and look forward to communicating with you if there are further questions.

**Comment by Chengfeng-Jia** [comment]
Thank you very much for your prompt response! After reviewing the code line you provided, I found the answer I was looking for.
